# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6da235c237764a0bfb30a59bef236b8db10312904ea82148712086421a272b665108576d7ac462655883f2945ab27987732b023249eff75638a7fce9abc0db95

test:
  secret_key_base: 38d844188a714237c3b3c6a7a2d621e6eb9bdf5047f9682847dd2f64cefcd469e8eeb413d5005bf60c5879720b4abf30f2cacafcb87e20e425ec02fac00018b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
